version: "4.1"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=postgresql://test_owner:ZbRLsfye78gO@ep-shrill-sky-a1c8kgfn.ap-southeast-1.aws.neon.tech/test
    platform: linux/amd64
    image: oohsai/basic-csv-app
